// <auto-generated />
using System;
using HouseDemo.DataAccess.EntityContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HouseDemo.DataAccess.Migrations
{
    [DbContext(typeof(HouseDbContext))]
    partial class HouseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HouseDemo.DataAccess.Models.House", b =>
                {
                    b.Property<Guid>("HouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("房屋Id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasComment("地址");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("int")
                        .HasComment("衛浴數");

                    b.Property<double>("BuildingSpace")
                        .HasColumnType("float")
                        .HasComment("建物坪數");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("創建時間");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasComment("創建者");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2")
                        .HasComment("刪除時間");

                    b.Property<string>("DeletedUser")
                        .HasColumnType("varchar(50)")
                        .HasComment("刪除者");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(100)")
                        .HasComment("描述");

                    b.Property<double?>("DiscountRate")
                        .HasColumnType("float")
                        .HasComment("折扣率");

                    b.Property<bool>("HasBalcony")
                        .HasColumnType("bit")
                        .HasComment("是否有陽台");

                    b.Property<string>("HouseName")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasComment("房屋名稱");

                    b.Property<int>("HouseType")
                        .HasColumnType("int")
                        .HasComment("房屋類型");

                    b.Property<double>("LandSpace")
                        .HasColumnType("float")
                        .HasComment("土地坪數");

                    b.Property<int>("LivinigRooms")
                        .HasColumnType("int")
                        .HasComment("廳數");

                    b.Property<double>("MainSpace")
                        .HasColumnType("float")
                        .HasComment("主坪數");

                    b.Property<int>("MaxFloor")
                        .HasColumnType("int")
                        .HasComment("最高樓層");

                    b.Property<int>("MinFloor")
                        .HasColumnType("int")
                        .HasComment("最低樓層");

                    b.Property<double?>("ParkingSpace")
                        .HasColumnType("float")
                        .HasComment("車位坪數");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasComment("價格");

                    b.Property<int>("Rooms")
                        .HasColumnType("int")
                        .HasComment("房間數");

                    b.Property<int>("TotalFloor")
                        .HasColumnType("int")
                        .HasComment("總樓層");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("修改時間");

                    b.Property<string>("UpdatedUser")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasComment("修改者");

                    b.Property<double>("Years")
                        .HasColumnType("float")
                        .HasComment("年");

                    b.HasKey("HouseId");

                    b.ToTable("Houses");
                });

            modelBuilder.Entity("HouseDemo.DataAccess.Models.HouseTag", b =>
                {
                    b.Property<Guid>("HouseTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FkHouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FkTagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("HouseTagId");

                    b.HasIndex("FkHouseId");

                    b.HasIndex("FkTagId");

                    b.ToTable("HouseTags", (string)null);
                });

            modelBuilder.Entity("HouseDemo.DataAccess.Models.Tag", b =>
                {
                    b.Property<Guid>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("標籤Id");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("創建時間");

                    b.Property<string>("CreatedUser")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasComment("創建者");

                    b.Property<DateTime?>("DeletedTime")
                        .HasColumnType("datetime2")
                        .HasComment("刪除時間");

                    b.Property<string>("DeletedUser")
                        .HasColumnType("varchar(50)")
                        .HasComment("刪除者");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasComment("標籤名稱");

                    b.Property<DateTime>("UpdatedTime")
                        .HasColumnType("datetime2")
                        .HasComment("修改時間");

                    b.Property<string>("UpdatedUser")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasComment("修改者");

                    b.HasKey("TagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("HouseDemo.DataAccess.Models.HouseTag", b =>
                {
                    b.HasOne("HouseDemo.DataAccess.Models.House", "House")
                        .WithMany("HouseTags")
                        .HasForeignKey("FkHouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HouseDemo.DataAccess.Models.Tag", "Tag")
                        .WithMany("HouseTags")
                        .HasForeignKey("FkTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("House");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("HouseDemo.DataAccess.Models.House", b =>
                {
                    b.Navigation("HouseTags");
                });

            modelBuilder.Entity("HouseDemo.DataAccess.Models.Tag", b =>
                {
                    b.Navigation("HouseTags");
                });
#pragma warning restore 612, 618
        }
    }
}
